[libraries]
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.1" }
picocli = { group = "info.picocli", name = "picocli", version = "4.7.6" }
fileupload = { group = "dev.mccue", name = "jdk-httpserver-fileupload", version = "2024.08.18" }
apache-httpclient = { group = "org.apache.httpcomponents.client5", name = "httpclient5", version = "5.4.1" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.16" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.16" }

[plugins]
lombok = { id = "io.freefair.lombok", version = "8.11" }
